# Generated by Django 4.1.1 on 2022-09-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='Choose author', to='catalog.author', verbose_name='Author'),
        ),
    ]
